apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: '1'

commonLabels:
    app: backend1
    app.kubernetes.io/component: backend1
    app.kubernetes.io/instance: backend1
    app.kubernetes.io/name: backend1
    app.kubernetes.io/part-of: api-workshop
    app.openshift.io/runtime: nodejs