kind: Service
apiVersion: v1
metadata:
  name: backend1
  labels:
    app: backend1
    app.kubernetes.io/component: backend1
    app.kubernetes.io/instance: backend1
    app.kubernetes.io/name: backend1
    app.kubernetes.io/part-of: api-workshop
    app.openshift.io/runtime-version: v1
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 9091
  type: ClusterIP
  selector:
    app: backend1
    deployment: backend1