apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
name: backends-app
namespace: user1-argocd
spec:
generators:
  - git:
      repoURL: 'https://github.com/yuvik777/nginx'
      revision: 'main'
      directories:
      - path: Deployment/Backend/layers/*
template:
    metadata:
      name: 'backend-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/yuvik777/nginx'
        targetRevision: 'main'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: user1-application
      syncPolicy:
        automated:
          prune: true
          selfHeal: true