kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend2
  labels:
    app: backend2
    app.kubernetes.io/component: backend2
    app.kubernetes.io/instance: backend2
    app.kubernetes.io/name: backend2
    app.kubernetes.io/part-of: api-workshop
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-namespace: api-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
        deployment: backend2
    spec:
      containers:
        - resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits: {}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 9091
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: backend2
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 9091
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-environment
                  key: BACKEBD_PORT
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          # Update with your image name
          image: 'quay.io/yuvalti/backend:v1'
          #
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600