apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/1
- backend/2
- frontend

configMapGenerator:
- name: app-environment
  literals:
    - BACKEBD_PORT=9091
    - PORT=8080
    - HOST1=backend1
    - HOST2=backend2
    - API_URL="Hello Red Hat!!!!!!!!"
- name: app-config
  files:
  - frontend/conf/default.conf
  - frontend/conf/entrypoint.sh
    